# Generated by Django 5.2.8 on 2025-11-06 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True, verbose_name='Название или IP')),
                ('ipadr', models.CharField(max_length=70, unique=True, verbose_name='IP адресс')),
                ('description', models.CharField(max_length=300, verbose_name='Описание')),
                ('hardware', models.CharField(max_length=300, verbose_name='Характеристики')),
                ('inwork', models.BooleanField(verbose_name='В работе')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('yearstart', models.CharField(blank=True, verbose_name='Год запуска')),
            ],
            options={
                'verbose_name': 'Сервер',
                'verbose_name_plural': 'Сервера',
            },
        ),
        migrations.CreateModel(
            name='VirtualServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Название')),
                ('description', models.CharField(max_length=300, verbose_name='Описание')),
                ('osVirt', models.CharField(max_length=70, verbose_name='Операционная система')),
                ('virthardware', models.CharField(max_length=300, verbose_name='Выделенно ресурсов')),
                ('ipadr', models.CharField(max_length=70, unique=True, verbose_name='IP адресс')),
                ('inwork', models.BooleanField(verbose_name='В работе')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('hardServer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.server', verbose_name='Физический сервер')),
            ],
            options={
                'verbose_name': 'Виртуальный сервер',
                'verbose_name_plural': 'Виртуальные сервера',
            },
        ),
    ]
