# Generated by Django 4.2.7 on 2025-11-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='yearstart',
            field=models.CharField(blank=True, max_length=30, verbose_name='Год запуска'),
        ),
    ]
