# Generated by Django 5.2.8 on 2025-11-06 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kadry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OxranaCam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CamName', models.CharField(max_length=30, verbose_name='Имя')),
                ('PodCam', models.CharField(max_length=10, verbose_name='Отдел')),
                ('CamIp', models.CharField(max_length=20, verbose_name='IP')),
                ('CamModel', models.CharField(max_length=30, verbose_name='Модель')),
                ('LogPasCam', models.CharField(max_length=15, verbose_name='Логин/Пароль')),
                ('RTSPCam', models.CharField(max_length=60, verbose_name='RTSP ссылка')),
                ('CamKoment', models.TextField(blank=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Камеру',
                'verbose_name_plural': 'Камеры',
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrintModel', models.CharField(max_length=30, verbose_name='Модель')),
                ('TipPrint', models.CharField(max_length=65, verbose_name='Тип принтера')),
                ('Mesto', models.CharField(max_length=65, verbose_name='Местонахождение')),
                ('SetPrint', models.CharField(max_length=70, verbose_name='IP адрес')),
                ('Kommentariy', models.TextField(blank=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Принтер',
                'verbose_name_plural': 'Принтеры',
            },
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventarNum', models.CharField(max_length=10, unique=True, verbose_name='Инвентарный номер')),
                ('KodPodrazdelenie', models.CharField(max_length=30, verbose_name='Код подразделения')),
                ('Podrazdelenie', models.CharField(max_length=30, verbose_name='Подразделение')),
                ('SetevoeImya', models.CharField(max_length=30, verbose_name='Сетевое имя')),
                ('TipPK', models.CharField(max_length=30, verbose_name='Тип ПК')),
                ('Konfiguracia', models.CharField(max_length=80, verbose_name='Конфигурация ПК')),
                ('OS', models.CharField(max_length=30, verbose_name='ОС')),
                ('Office', models.CharField(max_length=30, verbose_name='Офис')),
                ('VPNUser', models.CharField(max_length=30, verbose_name='VPN пользователь')),
                ('VPNIp', models.CharField(max_length=30, verbose_name='VPN Ip')),
                ('VPNPas', models.CharField(max_length=20, verbose_name='VPN пароль')),
                ('DataPokupki', models.CharField(max_length=30, verbose_name='Дата покупки')),
                ('Kommentariy', models.TextField(blank=True, verbose_name='Комментарий')),
                ('Polzovatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kadry.polzovatel', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Компьютер',
                'verbose_name_plural': 'Компьютеры',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('POlic', models.CharField(max_length=40, verbose_name='ПО')),
                ('POver', models.CharField(max_length=50, verbose_name='Версия')),
                ('POkey', models.CharField(max_length=50, verbose_name='Лицензия')),
                ('Polzovatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kadry.polzovatel', verbose_name='Пользователи')),
            ],
            options={
                'verbose_name': 'Лицензию',
                'verbose_name_plural': 'Лицензии',
            },
        ),
        migrations.CreateModel(
            name='TensoMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MailAdr', models.CharField(max_length=40, unique=True, verbose_name='Адрес почты')),
                ('MailPass', models.CharField(max_length=30, verbose_name='Пароль')),
                ('UserMail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kadry.polzovatel', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Почту',
                'verbose_name_plural': 'Почта',
            },
        ),
        migrations.CreateModel(
            name='User1C',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pas1C', models.CharField(max_length=20, verbose_name='Пароль')),
                ('DostupInt1C', models.CharField(blank=True, max_length=20, verbose_name='Доступ из интернета')),
                ('PasInt1C', models.CharField(blank=True, max_length=20, verbose_name='Пароль для интернет 1С')),
                ('Otdel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kadry.otdel', verbose_name='Отдел')),
                ('User1C', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kadry.polzovatel', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользователя 1С',
                'verbose_name_plural': 'Пользователи 1С',
            },
        ),
        migrations.CreateModel(
            name='VNCuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IpVNC', models.CharField(max_length=30, verbose_name='IP адрес')),
                ('HostVNC', models.CharField(max_length=40, verbose_name='HostName')),
                ('PasVNC', models.CharField(max_length=30, verbose_name='Пароль VNC')),
                ('UserVNC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kadry.polzovatel', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'VNC',
                'verbose_name_plural': 'VNC',
            },
        ),
    ]
