# Generated by Django 4.2.7 on 2025-11-10 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='KodPodrazdelenie',
        ),
    ]
