# Generated by Django 5.2.8 on 2025-11-06 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dolznost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dolznost', models.CharField(max_length=50, verbose_name='Должность')),
                ('Kommentariy', models.CharField(blank=True, max_length=70, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Otdel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Otdel', models.CharField(max_length=80, verbose_name='Отдел')),
                ('Kommentariy', models.TextField(max_length=80, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.CreateModel(
            name='Polzovatel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True, verbose_name='Сотрудник ФИО')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Kontakti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumTel', models.CharField(max_length=30, verbose_name='Телефон')),
                ('Podrazdel', models.CharField(blank=True, max_length=80, verbose_name='Подразделение')),
                ('MailAdress', models.CharField(blank=True, max_length=80, verbose_name='Подразделение')),
                ('pred', models.CharField(blank=True, max_length=30, verbose_name='ВИК/ТД')),
                ('photo', models.ImageField(default='kadry/photos/default.jpg', upload_to='kadry/photos', verbose_name='фотография')),
                ('kabinet', models.CharField(blank=True, max_length=15, verbose_name='Кабинет')),
                ('mob', models.CharField(max_length=30, verbose_name='Мобильный телефон')),
                ('Dolznost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kadry.dolznost', verbose_name='Должность')),
                ('Otdel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kadry.otdel', verbose_name='Отдел')),
                ('PolzovatelKontakti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kadry.polzovatel', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
