# Generated by Django 5.2.8 on 2025-11-06 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventar', '0001_initial'),
        ('kadry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontakti',
            name='MailAdress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventar.tensomail', verbose_name='Почта'),
        ),
    ]
