# Generated by Django 4.2.7 on 2025-11-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadry', '0002_alter_kontakti_mailadress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kontakti',
            name='pred',
        ),
        migrations.AlterField(
            model_name='kontakti',
            name='mob',
            field=models.CharField(blank=True, max_length=30, verbose_name='Мобильный телефон'),
        ),
    ]
